services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
